### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by Leinad4Mind** [Feneck91/Introduciator#11]
First of all, Merci for this! I really needed something like this!

I've installed on a 3.3.2 forum. And it doesn't seem to work. The user is not forced to introduce himself. :'(
I checked the code and even the permissions that should be set according the migration file doesn't appear on the permissions

**Comment by Feneck91** [comment]
I propose it on phpBB long time ago but it was refused. I must work on it again.
Link: [https://www.phpbb.com/customise/db/extension/introduciator/](Introduciator)

What is the version you install?

**Comment by Leinad4Mind** [comment]
I installed the last version here on github, on a 3.3.2 phpBB with php 7.3.17

**Comment by Feneck91** [comment]
I think that the master is not working. I'll back work on it, I stop this development 2 years ago after working on this version for so many hours! Where are you from?
Do you see Extension Tab with Instroduciator in the ACP panel?

**I have splitted:**
Ext/feneck91/introduciator/migrations/introduciator_migration_2_0_0.php
**to:**
Ext/feneck91/introduciator/migrations/v2_0_0/v2_0_0_data.php
Ext/feneck91/introduciator/migrations/v2_0_0/v2_0_0_schema.php

And it seems not working. I don't known why. I abandonned because I cannot found the problem. I MUST re-work on it.

**Comment by Leinad4Mind** [comment]
Thanks to take a look again. It can be really frustrating to not seeing our work approved neither receive better help from the approval team. 

I'm from Portugal, but lived some years on Switzerland and have family in France. I checked too phpBB fr looking for more news, but there wasn't.

And yes, I can see at ACP extensions all the options. But it doesn't redirect the user no matter what I select.
And the permissions migration isn't working since it doesn't appear at ACP permissions. Neither on the roles

**Comment by Leinad4Mind** [comment]
I made some overall improvements and make a PR. I'll start testing too now. Let see if we can make this work again.

**Comment by Leinad4Mind** [comment]
It seems its working now with my PR. But you should test it fully.

**Comment by Leinad4Mind** [comment]
Found a bug when intro explain is enabled at acp, when I try to create a post/topic, it gives an error instead of showing the new page.

"The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?"

EDIT: Bug fixed on the PR

**Comment by Leinad4Mind** [comment]
There is one thing that I don't like. The force feature, should force any action, even entering a forum or topic. At the moment it only forces when trying to create a topic or post.

Maybe adding on user_setup_after event some code. And maybe make this Force all action a new boolen at acp

**Comment by Feneck91** [comment]
I just back from Holidays. I'll have a look and make it work fine. I'll see your pull request.
I didn't understand the "Create a new migration file for acp module" ... more files, more migration... m1 / m2 ....etc
The Tab space is strange, with your code some text have not good aligment (use 4 for TAB).
This version does not work on phpBB 3.3.0, the tab that able to customize it is not showed, so the extension cannot be configured (like with my master code).

You create a fork... You want to make your own version of my extension or it just a need to make a pull request? I never use it.

I must make it work now and I'll try to make acceptation with phpBB again.
This extension run only when a user try to create a topic or reply to a message but it let user to see messages without beeing introduce.
The goal of "force" is to force to be introduced before write a message / topic into the forum.
Without "force" option, the user can write a message / topic into the forum without beeing introduced but
- the user cannot post more than one introduce into the introduce topic
- the moderator / administrator cannot remove the first message of the topic if it is the introduced topic, it must delete the all topic
- The button that make a link to the introduction of a user is active.
- All link are working fine
etc....

**Comment by Leinad4Mind** [comment]
You can accept the PR and then reformat the files. I use prettier for all my projects, so my vscode formats automatically on save.

I separate the migration files to be more organized and I can test if the modules are installed for example. And I renamed because it is the phpbb convention. And I've enhance the code on the permissions migration, you should at least take a look at that.

The twig syntax was improved too on all html files. There was many variables with  {var} instead of {{ var }}.
And I've enhanced the introduciator_explain_controller that wasn't working on my side.

I'm using return $this->helper->render('introduciator_explain.html', $message); instead of doing with set filename

It should work on 3.2.8, it will depend on the PHP you're using probably, since I'm using [] instead of array()
I tested on 3.3.2 and it is working great.

**Comment by Leinad4Mind** [comment]
About the tab extension not showing, did you remove the folder and add the new one, or overwrite above? Because such problem could occur if you overwrotted.

**Comment by Leinad4Mind** [comment]
I needed to create a fork so I could edit the code xD
And I did the PR so you could easely merge the code into your master. (If you want... but in my opinion I did a lot of good improvements)

**Comment by Feneck91** [comment]
Yes you make a good improvement and I will accept your PR but before I need to make it work and it's not good for the moment (my own code not working better ;-) )
I see the "$this->helper->render(" it is a better way.
Like splitting datas / schema / module / permissions migrations is really better ! I don't understand how phpBB know wich file should be run to make the migration...

Is a way to contact you by private message?
I use Wampserver 3.2.0 to test... working with 
Apache 2.4.41 Port 80- PHP 7.1.33
MySQL 8.0.18 Port 3308
MariaDB 10.4.10 Port 3306
PHP 5.6.40 for CLI (Command-Line Interface)

I'm C++ / C# developper, not web developper and it take me a lot of time  to understand how symfony is working and make the migration of this tool from MOD to EXTENSION (with more features).

The version is and must is 2.0.0 because the 2.0.0 has never been published. So the 2.0.0 doesn't exists, the 2.1.0 is the 2.0.0
skouat say that the code is not conforme to phpBB directives, trying to know more about that.
Indentation too.

May be I'll take a part of your code and apply it manually to my master, but in all case, I'll let your name into the header of each files.
I don't really know what I'll do but I'm sure I'll work on it to make it work and try to publish it again.
I need to make validate it by phpBB.

**Comment by Leinad4Mind** [comment]
"I don't understand how phpBB know wich file should be run to make the migration..."

I beleive it randomly picks the files but it will respect the depends_on on each file.
If you don't add an depends on then it will run when picked. Since some times it doesnt matter the order.

**Comment by Feneck91** [comment]
Ok, you reply to my question...
Is a way to contact you by private message?
Do you already try to ask a phpBB extension validation? It's really hard to have the validation.

**Comment by Leinad4Mind** [comment]
Send you a PM at phpBB

**Comment by Leinad4Mind** [comment]
A friend of mine did tried, it's a pain in the ass. I wrote more then 40 extensions and never tried myself, I don't have free time for that honestly.

**Comment by Feneck91** [comment]
It's cool because they see a lot of mistakes / security problems. And the extension is registered into the phpBB forum.
But they are really picky!!!!!!!!
Send you a message on Telegram (should install it and registered)...

**Comment by Feneck91** [comment]
I have made some change of my code and get your migrations files,  put back the option to enabled / disabled the extension.
Only enabled IF the configuration is ok.

**Comment by Feneck91** [comment]
With this version, could you test if the bug is closed? Or I think that you don't understant how it work.

**Comment by Leinad4Mind** [comment]
I'll check as soon as I've some free time. Being very busy with work.

**Comment by Feneck91** [comment]
It work now. I have submitted it on phpBB extension team.
